#!/usr/bin/env bash
## bkup-file
## Create a backup of a file in the same dir.
## ==================================== ##
## USAGE: ./$0 FILE
## ==================================== ##
cp --verbose --archive "${1?}"{,.$(date +%Y-%m-%dT%H%M%S%z).backup}
exit
