#!/usr/bin/env bash
## Only show WAN network activity, exclude LAN traffic.
## ==================================== ##
## AUTHOR: Ctrl-S
## CREATED: (Some time before 2025)
## MODIFIED: 2025-01-31 
## ==================================== ##
date -Is;
## iftop often needs elevated permissions.
## (Filter to exclude any traffic involved in broadcast, multicast, or designated IPv4 LAN address ranges.)
sudo iftop -ubytes -f 'not broadcast and not multicast and ( (outbound and (not dst net 10.0.0.0/8 or dst net 172.16.0.0/20 or dst net 192.168.0.0/16)) or (inbound and (not src net 10.0.0.0/8 or src net 172.16.0.0/20 or src net 192.168.0.0/16)) )'
