#!/usr/bin/env bash
## mylsblk
## A useful lsblk invocation.
## ==================================== ##
## LICENSE: BSD
## AUTHOR: Ctrl-S
## CREATED: 2024-08-28
## MODIFIED: 2023-11-24
## ==================================== ##
date -Is
params=( ## $ lsblk
	-o NAME,SIZE,FSTYPE,LABEL,MODEL,SERIAL
)
if [[ $# -ne 0 ]]; then ## Append script arguments if any were given.
	params=( "${params[@]}" "$@" )
fi
lsblk "${params[@]}"
## lsblk -o NAME,SIZE,FSTYPE,LABEL,MODEL,SERIAL
exit
